routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'language'], function () {
    Auth::routes();

    Route::get('/', 'ExpressionsController@index')->name('home');

    Route::resource('expressions', 'ExpressionsController')->only(['index' , 'show', 'store', 'update']);
});

Route::get('language/{local}', 'LanguageSwitcherController@switcher')->name('language.switcher')
    ->where('local', 'en|ru');

app/Expression.php
<?php

namespace App;

use Astrotomic\Translatable\Contracts\Translatable as TranslatableContract;
use Astrotomic\Translatable\Translatable;
use Illuminate\Database\Eloquent\Model;

class Expression extends Model implements TranslatableContract
{
    use Translatable;
    public $translatedAttributes = ['content'];
    protected $fillable = ['user_id'];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/ExpressionTranslation.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ExpressionTranslation extends Model
{
    public $timestamps = false;

    protected $fillable = ['content'];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function expressions()
    {
        return $this->hasMany(Expression::class);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ExpressionsController.php
<?php

namespace App\Http\Controllers;

use App\Expression;
use App\Http\Requests\ExpressionRequest;
use Illuminate\Http\Request;

class ExpressionsController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth')->only(['store', 'update', 'show']);
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $locale = app()->getLocale();
        $expressions = Expression::all();
        return view('expressions.index', compact('locale', 'expressions'));
    }

    /**
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show($id)
    {
        $locale = app()->getLocale();
        $expression = Expression::findOrFail($id);

        $expression_en = $expression->hasTranslation('en') ? $expression->translate('en')->content : null;
        $expression_ru = $expression->hasTranslation('ru') ? $expression->translate('ru')->content : null;
        $expression_de = $expression->hasTranslation('de') ? $expression->translate('de')->content : null;
        $expression_fr = $expression->hasTranslation('fr') ? $expression->translate('fr')->content : null;
        $expression_ja = $expression->hasTranslation('ja') ? $expression->translate('ja')->content : null;
        $expression_sp = $expression->hasTranslation('sp') ? $expression->translate('sp')->content : null;
        return view('expressions.show',
            compact('locale', 'expression', 'expression_en', 'expression_de',
                                  'expression_fr', 'expression_ja', 'expression_sp','expression_ru'));
    }

    /**
     * @param ExpressionRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(ExpressionRequest $request)
    {
        $expression = new Expression();
        $locale = $request->session()->get('locale');
        $expression->translateOrNew($locale)->content = $request->get('content');
        $expression->user_id = $request->user()->id;
        $expression->save();

        return back();
    }

    /**
     * @param Request $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update(Request $request, $id)
    {
        $expression = Expression::findOrFail($id);
        $expression->update($request->all());

        return redirect(route('expressions.show', ['expression' => $expression]));
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/LanguageSwitcherController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class LanguageSwitcherController extends Controller
{
    /**
     * @param Request $request
     * @param string $local
     * @return \Illuminate\Http\RedirectResponse
     */
    public function switcher(Request $request, string $local)
    {
        $request->session()->put('locale', $local);
        return back();
    }
}

resources/views/expressions/index.blade.php
@extends('layouts.app')

@section('content')

    <h2>@lang('All expressions'):</h2>

        @foreach($expressions as $expression)
            <p><a href="{{route('expressions.show', ['expression' => $expression])}}">{{$expression->content}}</a></p>
        @endforeach

    @auth()
    <hr>
    <h4 class="mt-5">@lang('Translation order'):</h4>
    <form method="post" action="{{route('expressions.store')}}" class="w-25 mt-3 mb-5">
        @csrf
        <div class="form-group">
            <label for="content">@lang('Write an expression'):</label>
            <textarea class="form-control @error('content') is-invalid @enderror" id="content" name="content" rows="3"></textarea>
            @error('content')
            <p class="text-danger">{{ $message }}</p>
            @enderror
        </div>
        <button type="submit" class="btn btn-success">@lang('Order translation')</button>
    </form>
    @endauth

@endsection

resources/views/expressions/show.blade.php
@extends('layouts.app')

@section('content')

    @can('viewIfNotTranslation', $expression)
        <p class="text-center h4">@lang('No translation')</p>
    @endcan

    @can('view', $expression)
        <h4 class="mb-3">@lang('Translation of the expression') "{{$expression->content}}":</h4>
        <div>
            @if($locale == "en")
                <p>@lang('Russian'): <span class="font-weight-bold">{{$expression_ru}}</span></p>
            @elseif($locale == "ru")
                <p>@lang('English'): <span class="font-weight-bold">{{$expression_en}}</span></p>
            @endif
            <p>@lang('German'): <span class="font-weight-bold">{{$expression_de}}</span></p>
            <p>@lang('French'): <span class="font-weight-bold">{{$expression_fr}}</span></p>
            <p>@lang('Japanese'): <span class="font-weight-bold">{{$expression_ja}}</span></p>
            <p>@lang('Spanish'): <span class="font-weight-bold">{{$expression_sp}}</span></p>
        </div>

        @if(Auth::check())
            <hr>
            <h4 class="mt-5">@lang('Translate'):</h4>
            <form method="post" action="{{route('expressions.update', ['expression' => $expression])}}" class="w-50 mt-3 mb-5">
                @csrf
                @method('put')

                @if($locale == "en")
                    <div class="form-group">
                        <label for="content">@lang('Russian'):</label>
                        <textarea class="form-control @error('content') is-invalid @enderror" id="content" name="content:ru" rows="1">{{$expression_ru}}</textarea>
                        @error('content')
                        <p class="text-danger">{{ $message }}</p>
                        @enderror
                    </div>

                @elseif($locale == "ru")
                    <div class="form-group">
                        <label for="content">@lang('English'):</label>
                        <textarea class="form-control @error('content') is-invalid @enderror" id="content" name="content:en" rows="1">{{$expression_en}}</textarea>
                        @error('content')
                        <p class="text-danger">{{ $message }}</p>
                        @enderror
                    </div>
                @endif

                <div class="form-group">
                    <label for="content">@lang('German'):</label>
                    <textarea class="form-control @error('content') is-invalid @enderror" id="content" name="content:de" rows="1">{{$expression_de}}</textarea>
                    @error('content')
                    <p class="text-danger">{{ $message }}</p>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="content">@lang('French'):</label>
                    <textarea class="form-control @error('content') is-invalid @enderror" id="content" name="content:fr" rows="1">{{$expression_fr}}</textarea>
                    @error('content')
                    <p class="text-danger">{{ $message }}</p>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="content">@lang('Japanese'):</label>
                    <textarea class="form-control @error('content') is-invalid @enderror" id="content" name="content:ja" rows="1">{{$expression_ja}}</textarea>
                    @error('content')
                    <p class="text-danger">{{ $message }}</p>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="content">@lang('Spanish'):</label>
                    <textarea class="form-control @error('content') is-invalid @enderror" id="content" name="content:sp" rows="1">{{$expression_sp}}</textarea>
                    @error('content')
                    <p class="text-danger">{{ $message }}</p>
                    @enderror
                </div>

                <button type="submit" class="btn btn-success">@lang('Translate')</button>
            </form>
        @endif
    @endcan

    <p><a href="{{route('expressions.index')}}">@lang('Back')</a></p>

@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Workshop of translators</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    @lang('Workshop of translators')
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        <select class="custom-select" onchange="location = this.value;">
                            <option @if (session('locale') == 'en') selected @endif value="{{route('language.switcher', 'en')}}">
                                EN
                            </option>
                            <option @if (session('locale') == 'ru') selected @endif value="{{route('language.switcher', 'ru')}}">
                                RU
                            </option>
                        </select>
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="container mt-4">
            @yield('content')
        </main>
    </div>
</body>
</html>